"""empty message

Revision ID: acd2cc68a712
Revises: bb0a74102395
Create Date: 2023-11-14 15:54:23.726473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd2cc68a712'
down_revision = 'bb0a74102395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('name')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
